### ISSUE TITLE
404 on refresh for pages

### ISSUE THREAD

**Issue by bpmct** [danielkellyio/awake-template#30]
Hi,

I am having getting a 404 error when I refresh a page (/about for example).

**Comment by danielkellyio** [comment]
whoops, was actually a result of the image required in the meta tag from your PR. Is because the featureImage doesn't come from the store on the about, categories, and contact page (only on the post pages). 
See fix here:
https://awake-template.netlify.app/_nuxt/uploads/2007798-640.jpg

In order to get the feature images correctly on those non blog post pages you'll need to do a head prop in the pages themselves. Feel free to PR for it if you have the chance. 

Thanks!

**Comment by bpmct** [comment]
Oh! Good find. Sorry about that 🤦‍♂️

I'll get that in soon :)
